/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    operators: OperatorAuthOperations;
  };
  blocks: {};
  collections: {
    operators: Operator;
    leads: Lead;
    clients: Client;
    interactions: Interaction;
    'client-interactions': ClientInteraction;
    deployments: Deployment;
    'billing-events': BillingEvent;
    jobs: Job;
    'policy-checks': PolicyCheck;
    'pipeline-events': PipelineEvent;
    'skill-versions': SkillVersion;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    operators: OperatorsSelect<false> | OperatorsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    interactions: InteractionsSelect<false> | InteractionsSelect<true>;
    'client-interactions': ClientInteractionsSelect<false> | ClientInteractionsSelect<true>;
    deployments: DeploymentsSelect<false> | DeploymentsSelect<true>;
    'billing-events': BillingEventsSelect<false> | BillingEventsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'policy-checks': PolicyChecksSelect<false> | PolicyChecksSelect<true>;
    'pipeline-events': PipelineEventsSelect<false> | PipelineEventsSelect<true>;
    'skill-versions': SkillVersionsSelect<false> | SkillVersionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'system-config': SystemConfig;
  };
  globalsSelect: {
    'system-config': SystemConfigSelect<false> | SystemConfigSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Operator;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface OperatorAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operators".
 */
export interface Operator {
  id: string;
  name: string;
  role: 'operator' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'operators';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: string;
  business_name: string;
  niche: string;
  city: string;
  state: string;
  website_url?: string | null;
  google_maps_url?: string | null;
  email?: string | null;
  phone?: string | null;
  decision_maker?: string | null;
  status:
    | 'new'
    | 'scored'
    | 'contacted'
    | 'replied_interested'
    | 'replied_objection'
    | 'demo_sent'
    | 'paid'
    | 'lost'
    | 'archived';
  audit_score?: number | null;
  audit_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  priority_tier?: ('hot' | 'warm' | 'low') | null;
  exclusion_reason?: string | null;
  source?: string | null;
  niche_city_key: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: string;
  lead?: (string | null) | Lead;
  business_name: string;
  contact_person?: string | null;
  email: string;
  phone?: string | null;
  plan: 'starter' | 'growth' | 'pro';
  plan_price_cents?: number | null;
  status: 'pending_payment' | 'onboarding' | 'active' | 'payment_failed' | 'grace_period' | 'suspended' | 'cancelled';
  niche: string;
  niche_template?: string | null;
  domain?: string | null;
  staging_url?: string | null;
  live_url?: string | null;
  checkout_link?: string | null;
  subscription_id?: string | null;
  onboarding_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  support_tier?: ('tier1' | 'tier2' | 'tier3') | null;
  edits_remaining?: number | null;
  edits_reset_at?: string | null;
  launched_at?: string | null;
  cancelled_at?: string | null;
  cancellation_reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interactions".
 */
export interface Interaction {
  id: string;
  lead: string | Lead;
  direction: 'inbound' | 'outbound';
  channel: 'email' | 'support_ticket' | 'whatsapp';
  message_type:
    | 'hook_email'
    | 'follow_up_1'
    | 'follow_up_2'
    | 'demo_email'
    | 'welcome'
    | 'support_reply'
    | 'monthly_report'
    | 'retention'
    | 'other';
  subject?: string | null;
  body?: string | null;
  status: 'draft' | 'pending_approval' | 'approved' | 'sent' | 'delivered' | 'bounced' | 'failed';
  reply_classification?:
    | ('interested' | 'not_interested' | 'objection' | 'question' | 'no_response' | 'angry' | 'legal_threat')
    | null;
  objection_type?: string | null;
  resend_message_id?: string | null;
  sent_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-interactions".
 */
export interface ClientInteraction {
  id: string;
  client: string | Client;
  direction?: ('inbound' | 'outbound') | null;
  channel?: string | null;
  message_type?:
    | ('support_request' | 'edit_request' | 'monthly_report' | 'retention' | 'proactive_fix' | 'escalation' | 'other')
    | null;
  subject?: string | null;
  body?: string | null;
  status?: ('open' | 'in_progress' | 'resolved' | 'escalated' | 'closed') | null;
  support_tier?: ('tier1' | 'tier2' | 'tier3') | null;
  skill_version?: string | null;
  human_approved?: boolean | null;
  resolved_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deployments".
 */
export interface Deployment {
  id: string;
  client: string | Client;
  type: 'demo' | 'initial_launch' | 'edit' | 'refresh' | 'redeploy';
  status: 'building' | 'ready' | 'deployed' | 'failed';
  template_version?: string | null;
  content_snapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  preview_url?: string | null;
  qa_results?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  data_isolation_ok?: boolean | null;
  human_approved?: boolean | null;
  human_approved_by?: string | null;
  deployed_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-events".
 */
export interface BillingEvent {
  id: string;
  client: string | Client;
  event_type:
    | 'checkout_complete'
    | 'renewal_success'
    | 'renewal_failed'
    | 'subscription_cancelled'
    | 'subscription_resumed'
    | 'grace_period_entered'
    | 'suspended';
  idempotency_key: string;
  amount_cents?: number | null;
  currency?: string | null;
  plan_at_event?: string | null;
  provider_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: string;
  job_type:
    | 'lead_gen'
    | 'follow_up_1'
    | 'follow_up_2'
    | 'demo_build'
    | 'onboarding'
    | 'monthly_report'
    | 'churn_check'
    | 'support_auto_reply'
    | 'billing_retry'
    | 'site_qa';
  lead?: (string | null) | Lead;
  client?: (string | null) | Client;
  status: 'queued' | 'running' | 'completed' | 'failed' | 'dead';
  attempts?: number | null;
  max_attempts?: number | null;
  run_at?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  failed_at?: string | null;
  error_message?: string | null;
  skill_version?: string | null;
  input_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  output_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-checks".
 */
export interface PolicyCheck {
  id: string;
  action_type: 'send_email' | 'send_demo' | 'launch_site' | 'respond_to_client' | 'apply_discount';
  lead?: (string | null) | Lead;
  client?: (string | null) | Client;
  interaction?: (string | null) | Interaction;
  rule_name: string;
  result: 'pass' | 'blocked' | 'requires_human_approval';
  blocking_reason?: string | null;
  override_by?: string | null;
  skill_version?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pipeline-events".
 */
export interface PipelineEvent {
  id: string;
  lead?: (string | null) | Lead;
  client?: (string | null) | Client;
  from_status?: string | null;
  to_status?: string | null;
  triggered_by?: string | null;
  skill_version?: string | null;
  decision_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  policy_check_result?: ('pass' | 'blocked' | 'bypassed') | null;
  human_approved?: boolean | null;
  human_approved_by?: string | null;
  human_approved_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-versions".
 */
export interface SkillVersion {
  id: string;
  skill_name: string;
  version: string;
  content_hash: string;
  deployed_by?: string | null;
  notes?: string | null;
  is_active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'operators';
        value: string | Operator;
      } | null)
    | ({
        relationTo: 'leads';
        value: string | Lead;
      } | null)
    | ({
        relationTo: 'clients';
        value: string | Client;
      } | null)
    | ({
        relationTo: 'interactions';
        value: string | Interaction;
      } | null)
    | ({
        relationTo: 'client-interactions';
        value: string | ClientInteraction;
      } | null)
    | ({
        relationTo: 'deployments';
        value: string | Deployment;
      } | null)
    | ({
        relationTo: 'billing-events';
        value: string | BillingEvent;
      } | null)
    | ({
        relationTo: 'jobs';
        value: string | Job;
      } | null)
    | ({
        relationTo: 'policy-checks';
        value: string | PolicyCheck;
      } | null)
    | ({
        relationTo: 'pipeline-events';
        value: string | PipelineEvent;
      } | null)
    | ({
        relationTo: 'skill-versions';
        value: string | SkillVersion;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'operators';
    value: string | Operator;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'operators';
    value: string | Operator;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operators_select".
 */
export interface OperatorsSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  id?: T;
  business_name?: T;
  niche?: T;
  city?: T;
  state?: T;
  website_url?: T;
  google_maps_url?: T;
  email?: T;
  phone?: T;
  decision_maker?: T;
  status?: T;
  audit_score?: T;
  audit_data?: T;
  priority_tier?: T;
  exclusion_reason?: T;
  source?: T;
  niche_city_key?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  id?: T;
  lead?: T;
  business_name?: T;
  contact_person?: T;
  email?: T;
  phone?: T;
  plan?: T;
  plan_price_cents?: T;
  status?: T;
  niche?: T;
  niche_template?: T;
  domain?: T;
  staging_url?: T;
  live_url?: T;
  checkout_link?: T;
  subscription_id?: T;
  onboarding_data?: T;
  support_tier?: T;
  edits_remaining?: T;
  edits_reset_at?: T;
  launched_at?: T;
  cancelled_at?: T;
  cancellation_reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interactions_select".
 */
export interface InteractionsSelect<T extends boolean = true> {
  id?: T;
  lead?: T;
  direction?: T;
  channel?: T;
  message_type?: T;
  subject?: T;
  body?: T;
  status?: T;
  reply_classification?: T;
  objection_type?: T;
  resend_message_id?: T;
  sent_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-interactions_select".
 */
export interface ClientInteractionsSelect<T extends boolean = true> {
  id?: T;
  client?: T;
  direction?: T;
  channel?: T;
  message_type?: T;
  subject?: T;
  body?: T;
  status?: T;
  support_tier?: T;
  skill_version?: T;
  human_approved?: T;
  resolved_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deployments_select".
 */
export interface DeploymentsSelect<T extends boolean = true> {
  id?: T;
  client?: T;
  type?: T;
  status?: T;
  template_version?: T;
  content_snapshot?: T;
  preview_url?: T;
  qa_results?: T;
  data_isolation_ok?: T;
  human_approved?: T;
  human_approved_by?: T;
  deployed_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-events_select".
 */
export interface BillingEventsSelect<T extends boolean = true> {
  id?: T;
  client?: T;
  event_type?: T;
  idempotency_key?: T;
  amount_cents?: T;
  currency?: T;
  plan_at_event?: T;
  provider_data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  id?: T;
  job_type?: T;
  lead?: T;
  client?: T;
  status?: T;
  attempts?: T;
  max_attempts?: T;
  run_at?: T;
  started_at?: T;
  completed_at?: T;
  failed_at?: T;
  error_message?: T;
  skill_version?: T;
  input_data?: T;
  output_data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-checks_select".
 */
export interface PolicyChecksSelect<T extends boolean = true> {
  id?: T;
  action_type?: T;
  lead?: T;
  client?: T;
  interaction?: T;
  rule_name?: T;
  result?: T;
  blocking_reason?: T;
  override_by?: T;
  skill_version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pipeline-events_select".
 */
export interface PipelineEventsSelect<T extends boolean = true> {
  id?: T;
  lead?: T;
  client?: T;
  from_status?: T;
  to_status?: T;
  triggered_by?: T;
  skill_version?: T;
  decision_data?: T;
  policy_check_result?: T;
  human_approved?: T;
  human_approved_by?: T;
  human_approved_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-versions_select".
 */
export interface SkillVersionsSelect<T extends boolean = true> {
  id?: T;
  skill_name?: T;
  version?: T;
  content_hash?: T;
  deployed_by?: T;
  notes?: T;
  is_active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-config".
 */
export interface SystemConfig {
  id: number;
  /**
   * Maps to doc 14 implementation phases (1-7)
   */
  current_phase: number;
  email_approval_required: boolean;
  demo_approval_required: boolean;
  /**
   * Never set to false — launch gate is permanent
   */
  launch_approval_required: boolean;
  active_niche: string;
  active_cities:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  dodo_checkout_links?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  maintenance_mode?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-config_select".
 */
export interface SystemConfigSelect<T extends boolean = true> {
  current_phase?: T;
  email_approval_required?: T;
  demo_approval_required?: T;
  launch_approval_required?: T;
  active_niche?: T;
  active_cities?: T;
  dodo_checkout_links?: T;
  maintenance_mode?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}